### ISSUE TITLE
PyArrow Dependency whe using Parquet format

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/bridge#65]
Using SciDB `22.5` with Arrow `11.0.0`:
```
> iqq "store(apply(build(<x:int64>[i=1:100:0:10], i), y, double(x*x)), foo)"
> iqq "xsave(foo, 'file:///tmp/bridge/arrow/11', format:'parquet')"
> cat /tmp/bridge/arrow/11/metadata 
attribute	ALL
compression	lz4
format	parquet
index_split	100000
namespace	public
schema	<x:int64,y:double> [i=1:100:0:10]
version	1
```
Then try to read the array from Python using PyArrow `4.0.0`:
```
> pip3 install --user pyarrow==4.0.0
> VER=11; python3 -c "import pyarrow, scidbbridge; print(pyarrow.__version__); ar = scidbbridge.Array('file:///tmp/bridge/arrow/$VER'); print(ar.read_index()); print(ar.get_chunk(31).to_pandas())"
4.0.0
    i
0   1
1  11
2  21
3  31
4  41
5  51
6  61
7  71
8  81
9  91
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/proj/bridge/py_pkg/scidbbridge/__init__.py", line 327, in to_pandas
    self.table.to_pandas(), self.array.schema, self.coords)
  File "/proj/bridge/py_pkg/scidbbridge/__init__.py", line 322, in table
    compression=self.array.metadata['compression'])
  File "/proj/bridge/py_pkg/scidbbridge/driver.py", line 165, in read_table
    return pyarrow.parquet.read_table(path)
  File "/root/.local/lib/python3.6/site-packages/pyarrow/parquet.py", line 1732, in read_table
    use_pandas_metadata=use_pandas_metadata)
  File "/root/.local/lib/python3.6/site-packages/pyarrow/parquet.py", line 1610, in read
    use_threads=use_threads
  File "pyarrow/_dataset.pyx", line 458, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 2889, in pyarrow._dataset.Scanner.to_table
  File "pyarrow/error.pxi", line 141, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
OSError: Unexpected end of stream
```
If the array is saved in `arrow` format this works fine.
If we use PyArrow `>4.0.0` this works fine:
```
> pip3 install --user pyarrow==5.0.0
> VER=11; python3 -c "import pyarrow, scidbbridge; print(pyarrow.__version__); ar = scidbbridge.Array('file:///tmp/bridge/arrow/$VER'); print(ar.read_index()); print(ar.get_chunk(31).to_pandas())"
5.0.0
    i
0   1
1  11
2  21
3  31
4  41
5  51
6  61
7  71
8  81
9  91
    x       y   i
0  31   961.0  31
1  32  1024.0  32
2  33  1089.0  33
3  34  1156.0  34
4  35  1225.0  35
5  36  1296.0  36
6  37  1369.0  37
7  38  1444.0  38
8  39  1521.0  39
9  40  1600.0  40
```

**Comment by rvernica** [comment]
If the array is saved (`xsave`) using Arrow `3.0.0`, the array can be read using PyArrow `4.0.0` or `5.0.0`

So, the PyArrow library is forward compatible - newer library versions can read files written by older library versions - but not backward compatible - older library versions cannot read files written by newer library versions.

The solution is for the Python packages such as `scidb-bridge`, `scidb-py`, `scidb-strm` to require PyArrow `>4.0.0`

**Comment by rvernica** [comment]
This fix is already implemented [here](https://github.com/Paradigm4/bridge/blob/e64c1437d34c67d06db5b71180c113a3e6302033/py_pkg/setup.py#L55)
