### ISSUE TITLE
Python scidbbridge - non-unique column error with attribute of delta

### ISSUE THREAD

**Issue by mcolosimo-p4** [Paradigm4/bridge#8]
The new encoding of dimensions as delta introduces a *hidden* column/field that is called `delta`. 

This works fine in scidb

```bash
iquery -aq "xsave( filter( apply( build(<v:int64>[i=0:9:0:5; j=10:19:0:5], j + i), delta, double(v*v)), i >= 5 and delta % 2 = 0), 'file:///tmp/bridge/foodelta')"
{chunk_no,dest_instance_id,source_instance_id} val
iquery -aq "xinput('file:///tmp/bridge/foodelta')"
{i,j} v,delta
{5,11} 16,256
{5,13} 18,324
```

but in Python:

```python
>>> import scidbbridge
>>> ar = scidbbridge.Array('file:///tmp/bridge/foodelta')
>>> ar.schema
Schema(name=None, atts=(Attribute(name='v', type_name='int64', not_null=False, default=None, compression=None), Attribute(name='delta', type_name='double', not_null=False, default=None, compression=None)), dims=(Dimension(name='i', low_value=0, high_value=9, chunk_overlap=0, chunk_length=5), Dimension(name='j', low_value=10, high_value=19, chunk_overlap=0, chunk_length=5)))
>>>ch.to_pandas()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mcolosimo/miniconda3/lib/python3.8/site-packages/scidbbridge/__init__.py", line 270, in to_pandas
    return pyarrow.Table.to_pandas(self.table)
  File "pyarrow/array.pxi", line 751, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow/table.pxi", line 1668, in pyarrow.lib.Table._to_pandas
  File "/home/mcolosimo/miniconda3/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 791, in table_to_blockmanager
    columns = _deserialize_column_index(table, all_columns, column_indexes)
  File "/home/mcolosimo/miniconda3/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 906, in _deserialize_column_index
    columns = _flatten_single_level_multiindex(columns)
  File "/home/mcolosimo/miniconda3/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 1147, in _flatten_single_level_multiindex
    raise ValueError('Found non-unique column index')
ValueError: Found non-unique column index
```

This might be a pain to fix in Python, given the code:

```Python
        pd['delta'] = coord2delta(pd, self.array.schema.dims, self.coords)

        self._table = pyarrow.Table.from_pandas(pd, schema)
```

We might need to just rename it to something that is NOT an allowable attribute name, maybe `@delta`.

**Comment by apoliakov** [comment]
@rvernica I think this makes sense - basically the problem is that the thing is called "delta" and so if you have any other thing called "delta" it collides. Let's see if we can rename it?

**Comment by mcolosimo-p4** [comment]
As a fallback maybe include it in the metadata file:

> delta_field deltaFieldNameIsThis

As for how to generate it, maybe something like:

```python
>>> from hashlib import md5
>>> h =  md5(str(ar.schema).encode('utf-8')).hexdigest()
>>> f"_delta_{h[0:8]}"
'_delta_3d67a5b5'
```

With some checks to see if that exists as an attribute, and if so just keep adding characters from the hash.

**Comment by rvernica** [comment]
It looks like using `@delta` for the cell delta values does the trick. `@delta` is a valid column name in the Arrow schema but not in the SciDB schema

**Comment by apoliakov** [comment]
Rares - I like that choice. Let's do that.
